# Generated by Django 6.0.3 on 2026-03-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventconsumed_exception_eventconsumed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(
                choices=[
                    ("text extracted from resource", "Text Extracted From Resource"),
                    (
                        "extracted text clean up finished",
                        "Extracted Text Clean Up Finished",
                    ),
                    ("chat message submitted", "Chat Message Submitted"),
                    (
                        "knowledge graph update requested",
                        "Knowledge Graph Update Requested",
                    ),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="entity",
            field=models.CharField(
                choices=[("resource", "Resource"), ("chat", "Chat")], max_length=50
            ),
        ),
    ]
