# Generated by Django 6.0.3 on 2026-03-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_populate_default_textextractionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_provider', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'date_created'],
            },
        ),
    ]
