# Generated by Django 6.0.3 on 2026-03-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_seed_embedding_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(default='openai', max_length=255),
        ),
    ]
