# Generated by Django 6.0.3 on 2026-03-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_llmconfig_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OPENROUTER'), ('groq', 'GROQ'), ('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC')], default='openai', max_length=255),
        ),
        migrations.CreateModel(
            name='ResourceChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_chats', to='kb.resource')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
