# Generated by Django 6.0.3 on 2026-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0009_resource_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
