# Generated by Django 6.0.3 on 2026-03-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0011_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeGraphConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "package_name",
                    models.CharField(default="djangorag.lightrag_app", max_length=255),
                ),
                (
                    "update_trigger",
                    models.CharField(
                        choices=[
                            ("always", "Each time I send a message"),
                            ("llm_intent", "When I ask for an update explicitly"),
                        ],
                        default="always",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openrouter", "OPENROUTER"),
                    ("groq", "GROQ"),
                    ("openai", "OPENAI"),
                    ("anthropic", "ANTHROPIC"),
                    ("lmstudio", "LMSTUDIO"),
                ],
                default="openai",
                max_length=255,
            ),
        ),
    ]
