# Generated by Django 6.0.3 on 2026-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0013_alter_knowledgegraphconfig_package_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgegraphconfig",
            name="package_name",
            field=models.CharField(default="django_lightrag", max_length=255),
        ),
    ]
