# Generated by Django 6.0.3 on 2026-03-23 00:00

from django.db import migrations, models


def seed_default_search_config(apps, schema_editor):
    SearchConfig = apps.get_model("kb", "SearchConfig")
    SearchConfig.objects.get_or_create(
        name="semantic search",
        defaults={
            "package_path": "kb.services.search_engines.semantic_search.search",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0014_alter_knowledgegraphconfig_package_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("package_path", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.RunPython(seed_default_search_config, migrations.RunPython.noop),
    ]
